<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adders' => 'Адрес',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Categoryname' => 'Название категории',
    'Delete' => 'Удалить',
    'First Name' => 'Имя',
    'Name' => 'Наименование',
    'Reset' => 'Сброс',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Update' => 'Обновить',
    'Are you sure you want to delete this item?' => '',
    'Email' => 'Электронная почта',
    'ID' => '',
    'Last Name' => 'Фамилия',
    'Password' => 'Пароль',
    'Password Repeat' => 'Повторите пароль',
    'Select issue date ...' => '',
    'The requested page does not exist.' => '',
    'Remember Me' => 'Запомнить меня'
];
